### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException in giiant crud generator

### ISSUE THREAD

**Issue by paultipper** [phundament/app#162]
I'm trying to generate a CRUD from a model using the giiant CRUD generator, but when I do so, I get the following error:

'yii\base\InvalidParamException' with message 'Invalid path alias: @backend/views' in C:\php\medexpenses\vendor\yiisoft\yii2\BaseYii.php:152

The stack trace is as follows:

#0 C:\php\medexpenses\vendor\schmunk42\yii2-giiant\crud\Generator.php(175): yii\BaseYii::getAlias('@backend/views') #1 C:\php\medexpenses\vendor\yiisoft\yii2-gii\generators\crud\Generator.php(166): schmunk42\giiant\crud\Generator->getViewPath() #2 C:\php\medexpenses\vendor\yiisoft\yii2-gii\controllers\DefaultController.php(45): yii\gii\generators\crud\Generator->generate() #3 [internal function]: yii\gii\controllers\DefaultController->actionView('giiant-crud') #4 C:\php\medexpenses\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array) #5 C:\php\medexpenses\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array) #6 C:\php\medexpenses\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('view', Array) #7 C:\php\medexpenses\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('gii/default/vie...', Array) #8 C:\php\medexpenses\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #9 C:\php\medexpenses\web\index.php(12): yii\base\Application->run() #10 {main}

I've only just installed giiant this afteroon using Composer, so perhaps I missed a configuration step.

Any ideas?

**Comment by paultipper** [comment]
Sorry - I've posted this issue in the wrong place! I'll raise this against the schmunk42/yii2-giiant app now.
